# Generated by Django 4.2.1 on 2024-11-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='supportstaff',
            options={'verbose_name': 'Support Staff', 'verbose_name_plural': 'Support Staff'},
        ),
        migrations.AddField(
            model_name='supportlog',
            name='action',
            field=models.CharField(choices=[('Created', 'Ticket Created'), ('Assigned', 'Ticket Assigned'), ('Status Update', 'Status Updated'), ('Comment', 'Comment Added'), ('Escalated', 'Ticket Escalated'), ('Resolved', 'Ticket Resolved'), ('Reopened', 'Ticket Reopened')], default='Comment', max_length=50),
        ),
        migrations.AddField(
            model_name='supportlog',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='current_active_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='max_active_tickets',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='support_level',
            field=models.IntegerField(choices=[(1, 'Level 1 - First Response'), (2, 'Level 2 - Technical'), (3, 'Level 3 - Specialist'), (4, 'Level 4 - Manager')], default=1),
        ),
        migrations.AlterField(
            model_name='supportstaff',
            name='department',
            field=models.CharField(choices=[('Customer Service', 'Customer Service'), ('Technical Support', 'Technical Support'), ('Billing Support', 'Billing Support'), ('Emergency Response', 'Emergency Response'), ('Field Operations', 'Field Operations')], max_length=100),
        ),
    ]
