# Generated by Django 4.2.1 on 2024-11-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('Gas Leak', 'Gas Leak'), ('Billing Issue', 'Billing Issue'), ('New Connection', 'New Connection'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
    ]
