# Generated by Django 4.2.1 on 2024-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
